### ISSUE TITLE
Delay while resizing sidebar

### ISSUE THREAD

**Issue by CottageCabbage** [CottageCabbage/vu-dooit#39]
For the open-close animation, I've used `transition: width 0.2s`. It makes it prettier.

```css
#wide-sidebar {
  overflow-x: hidden;
  resize: horizontal;
  max-width: 300px;
  transition: background 0s, width 0.2s; // THIS RIGHT HERE
}
```

This creates an annoying delay while resizing it with through dragging.

Not completely sure how to fix this, but I think switching the `width 0.2s` in `transition` to `flex`/`flex-grow`/`flex-shrink` (and doing the same to how the sidebar's animation class) maybe would work? Remember to test later
